{% set name = "GES-echem-suite" %}
{% set version = "0.2.1a" %}



package:
  name: "{{ name|lower }}"
  version: "{{ version }}"



source:
  url: https://github.com/GES-compchem/{{ name }}/archive/refs/tags/{{ version }}.zip
  
build:
  noarch: python
  number: 0



requirements:
  host:
    - python>=3.7
    - pip
    - setuptools

  run:
    - python>=3.7
    - numpy
    - pandas>=1.3.0
    - scipy
    - matplotlib
  
test:
  imports:
    - pytest>=6.0
    - pytest-cov>=2.0
    - tox

about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:



extra:
  recipe-maintainers:
    - GES-compchem