{% set name = "GES-echem-suite" %}
{% set version = "0.1.4a" %}



package:
  name: "{{ name|lower }}"
  version: "{{ version }}"



source:
  url: https://github.com/GES-compchem/{{ name }}/archive/refs/tags/{{ version }}.zip

build:
  number: 0



requirements:
  host:
    - python>=3.8
    - pip
    - setuptools
    - numpy
    - pandas
    - scipy
    - matplotlib

  run:
    - python>=3.8
    - numpy
    - pandas
    - scipy
    - matplotlib


about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:



extra:
  recipe-maintainers:
    - GES-compchem